spring:
  datasource:
    url: jdbc:mysql://localhost:3306/delivery_service?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: rbghrn7670
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      data-source-properties:
        rewriteBatchedStatements: true
  thymeleaf:
    prefix: classpath:/static/
  mvc:
    view:
      suffix: .html
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

logging:
#  config: classpath:logging-config.xml
  level:
    org:
      hibernate:
        type: trace


springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /api/**