### 로그인
POST http://{{host}}/api/user/login
Content-Type: application/json

{
  "id": "ghhan7",
  "password" :"deliveryTest123~"
}

> {% client.global.set("authorizationToken", String(response.body)); %}

### 회원가입
POST http://{{host}}/api/user/sign-up
Content-Type: application/json

{
  "id": "ghhan7",
  "password" :"deliveryTest123~",
  "userName" : "한규호"
}

### 유저 조회
GET http://{{host}}/api/user/info/ghhan
X-AUTH-TOKEN: {{authorizationToken}}


### 테스트
GET http://{{host}}/api/user/test
X-AUTH-TOKEN: {{authorizationToken}}



### 주문조회
GET http://{{host}}/api/order?startDate=20221207&endDate=20221209
X-AUTH-TOKEN: {{authorizationToken}}