### 로그인
POST http://{{host}}/api/user/login
Content-Type: application/json

{
  "id": "ghhan",
  "password" :"ghhan123456~!"
}

> {% client.global.set("authorizationToken", String(response.body)); %}

### 회원가입
POST http://{{host}}/api/user/sign-up
Content-Type: application/json

{
  "id": "ghhan",
  "password" :"ghhan123456~!",
  "userName" : "한규호"
}

### 주문조회
GET http://{{host}}/api/order?startDate=20221207&endDate=20221209
Content-Type: application/json
X-AUTH-TOKEN: {{authorizationToken}}


### 주문수정
PUT http://{{host}}/api/order/2
Content-Type: application/json
X-AUTH-TOKEN: {{authorizationToken}}

{
  "admCd": "4119011000",
  "baseAddress": "경기도 부천시 소사본동11112313123",
  "detailAddress": "10-1123123"
}

### 배송주소 조회
GET http://{{host}}/api/order/search-address?keyword=중동로 71번길&currentPage=1&countPerPage=20
Content-Type: application/json
X-AUTH-TOKEN: {{authorizationToken}}